apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/temporal.io_temporalclusters.yaml
- bases/temporal.io_temporalclusterclients.yaml
- bases/temporal.io_temporalnamespaces.yaml
- bases/temporal.io_temporalschedules.yaml
#+kubebuilder:scaffold:crdkustomizeresource
configurations:
- kustomizeconfig.yaml

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_clusters.yaml
#- patches/webhook_in_clusterclients.yaml
#- patches/webhook_in_namespaces.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_clusters.yaml
#- patches/cainjection_in_clusterclients.yaml
#- patches/cainjection_in_namespaces.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch


